### PR TITLE
Handle "external-only" bundles created with browserify -r. Fixes #41

### LINKED ISSUE #41: Manage external package only bundle
I'm using the `external` functionality of browserify to generate my javascript files. It produce two files: `app.js` and `vendor.js`. Using disc with the `app.js` works perfectly. But it's do not work on the `vendor.js` :sob:

Here the blueprint of how I generate my two packages:

``` js
// app.js 
var b = browserify('client.js', {...});

// I externalyse some dependencies
var dependencies = ['lodash', 'react', 'react-router'];
for (var i in dependencies) {
     b.external(dependencies[i]);
}

b.bundle() // It's a gulp task, so the rest of the file is not the point of this code 
```

``` js
// vendor.js
var b = browserify(null,  {...}); // Here is the issue I think

var dependencies = ['lodash', 'react', 'react-router']; // same array of external dependencies as before
for (var i in dependencies) {
    b.require(dependencies[i]);
}

b.bundle() 
```

I guess is that`disc` cannot work on my `vendor.js` file because there no entry point in this bundle `var b = browserify(null,  {...});`.

If I build all my dependencies in my `app.js` bundle, everything works.

Tell me if you want my `vendor.js` file.

### PR DESCRIPTION
**Pull request by SystemParadox**

### CODE REVIEW

**Comment by irae** [comment]
This works for me, would close #20

**Comment by jbalboni** [comment]
This works for me, too, and I would love to see it merged and released on npm. I'm stuck running a locally built version of discify with this branch because of this issue.

**Comment by cormacrelf** [comment]
+1, would love this.

**Comment by c-f-h** [comment]
Would be nice to have this merged.

**Comment by juandopazo** [comment]
👍

**Comment by lyret** [comment]
Would love to see this merged.

**Comment by cody-greene** [comment]
What's holding this back?

**Comment by niallwingham** [comment]
I recently published a built version of this pull request on my github, so until it's merged you can `npm install https://github.com/niallwingham/disc.git` if you want to avoid building the fork locally.

**Comment by toddlucas** [comment]
Thanks for this fix @niallwingham. It solves my vendor.js issue.

**Pull request merged**
