### PR TITLE
Updated deps, added travis ci support to ensure coverage

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by ArtskydJ** [comment]
This PR breaks the installation.

`rework` breaks...

```bash
> disc@1.3.2 rework C:\Users\Michael\Github\disc
> node lib/bundle-css > build/style.css

C:\Users\Michael\Github\disc\lib\bundle-css.js:9
  .use(rework.inline(__dirname + '/../img'))
              ^

TypeError: rework.inline is not a function
    at Object.<anonymous> (C:\Users\Michael\Github\disc\lib\bundle-css.js:9:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```
...and `autoprefixer` breaks.
```bash
> disc@1.3.2 rework C:\Users\Michael\Github\disc
> node lib/bundle-css > build/style.css

C:\Users\Michael\Github\disc\lib\bundle-css.js:12
css = autoprefixer.process(
                   ^

TypeError: autoprefixer.process is not a function
    at Object.<anonymous> (C:\Users\Michael\Github\disc\lib\bundle-css.js:12:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by paulirish** [comment]
I get the same error: 
image

**Comment by amilajack** [comment]
It seems the `inline` functionality of rework was migrated to [rework-plugin-inline](https://github.com/reworkcss/rework-plugin-inline)

**Comment by yoshuawuyts** [comment]
Added as f862d53. Thanks!

**Pull request closed without merging**
